name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # don't run tests
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
  
  deploy-to-github-pages:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    # publishes Blazor project to the release-folder
    - name: list files
      run: |
        echo '::echo::on'
        pwd
        echo '::set-output name=action_ls::enabled'
        ls -R      
    - name: Publish .NET Core Project
      # /home/runner/work/formulas
      run: dotnet publish Formulas.csproj -c Release -o release --nologo
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with: 
        folder: release/wwwroot
