name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore        
    - name: Publish .NET Core Project
      # /home/runner/work/formulas
      run: dotnet publish /home/runner/work/formulas/formulas/Formulas/Formulas.csproj -c Release -o release --nologo
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with: 
        folder: release/wwwroot
        repository-name: serkankose/serkankose.github.io
